name: Run JIRA Sync Unit Tests

on: [push]

jobs:
  test_jira_sync:
    name: test_jira_sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test JIRA sync
        uses: .
        with:
          entrypoint: ./test_sync_to_jira.py
